#pragma once

template <class T>
class CProxy_ICudaKernelEvents : public IConnectionPointImpl<T, &__uuidof( _ICudaKernelEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
